services:
  database:
    container_name: ${MONGODB_HOST}
    image: "mongo:7.0.2"
    restart: always
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATASOURCE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}

  mongo-express:
    image: "mongo-express"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATASOURCE_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATASOURCE_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_CONNECTION_STRING}

  # database:
  #   container_name: ${POSTGRES_HOST}
  #   image: "postgres:15.2"
  #   ports:
  #     - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  #   environment:
  #     - "POSTGRES_DB=${POSTGRES_DB_NAME}"
  #     - "POSTGRES_USER=${DATASOURCE_USER}"
  #     - "POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pg@mail.com
  #     PGADMIN_DEFAULT_PASSWORD: password

  app:
    container_name: ${APPLICATION_NAME}
    build: ./
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - APPLICATION_NAME=${APPLICATION_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USER=${DATASOURCE_USER}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_DRIVER=${DATASOURCE_DRIVER}
      - DATASOURCE_DIALECT=${DATASOURCE_DIALECT}
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    restart: on-failure
    depends_on:
      - database
